### ISSUE TITLE
[Feat] 3개의 마이크로 서비스 연결하기

### ISSUE THREAD

**Issue by nayoonk928** [nayoonk928/newsfeed-system#21]
### Description
* 3개의 마이크로 서비스가 서로 통신하게 하기

### TODO
- [x] API Gateway 구축
  - [x] 공통 인증 필터 구현
- [x] User Service 에서 제공해야하는 REST API 만들기
- [x] Activity Service에서 제공해야하는 REST API 만들기
- [x] News Feed Service 에서 제공해야하는 REST API 만들기
